version: 2
jobs:
   build:
     docker:
       - image: circleci/php:7.1-jessie-node
     steps:
       - checkout
       - run: echo "hello world"
   deploy:
       machine:
         enabled: true
       steps:
          - add_ssh_keys:
                     fingerprints:
                       - "5a:3e:5f:7f:35:1c:26:8b:71:57:92:bf:f4:9b:3e:b9"
          - run:
             name: Deploy Over SSH
             command: |
               ssh -t $SSH_USER@$SSH_HOST "cd public_html/inspirecms && git pull origin master"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:

          requires:
            - build
          filters:
            branches:
              only: master