version: 2
jobs:
   build:
     docker:
       - image: circleci/php:7.1-jessie-node
     working_directory: ~/laravel
     steps:
       #https://askubuntu.com/questions/594656/how-to-install-the-latest-versions-of-nodejs-and-npm
       #We are using Node JS 6 because that's the current version on our local vagrant/homestead machines
       - run:
          name: Download NodeJS v6
          command: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
       #sqlite needed for laravel database
       #nodejs6 needed to run `npm run watch` later
       - run:
          name: Install PHP sqlite and nodejs 6
          command: sudo apt-get install -y libsqlite3-dev nodejs

       - run:
          name: Update composer to latest version
          command: composer self-update

       - restore_cache:
           keys:
             - composer-v1-{{ checksum "composer.json" }}
             - composer-v1-
       - run: composer install -n --prefer-dist --ignore-platform-reqs
       - save_cache:
           key: composer-v1-{{ checksum "composer.json" }}
           paths:
             - vendor

       - restore_cache:
           key: dependency-cache-{{ checksum "package.json" }}
       - run:
           name: Install NodeJS Packages
           command:  npm install
       - save_cache:
           key: dependency-cache-{{ checksum "package.json" }}
           paths:
             - ./node_modules

       - run:
           name: Create SQLite Database
           command: touch database/database.sqlite

       - run:
           name: Migrate Laravel Database
           command: php artisan migrate --env=testing --force

       - run:
           name: Compile Javascript & CSS for Browser Testing
           command: npm run production

       - run:
           name: Start Chrome Driver
           command: ./vendor/laravel/dusk/bin/chromedriver-linux
           background: true

       - run:
           name: Run Laravel Server
           command: php artisan serve
           background: true

       - run:
           name: Test 1 - Run Phpunit for Server-Side HTTP Requests & PHP Unit Testing
           command: vendor/bin/phpunit
   deploy:
       machine:
         enabled: true
       steps:
          - add_ssh_keys:
                     fingerprints:
                       - "5a:3e:5f:7f:35:1c:26:8b:71:57:92:bf:f4:9b:3e:b9"
          - run:
             name: Deploy Over SSH
             command: |
               ssh -t $SSH_USER@$SSH_HOST "cd public_html/inspirecms && git pull origin master"
          - add_ssh_keys:
                     fingerprints:
                       - "0c:33:a8:8c:40:06:fa:ae:13:c8:63:a6:e7:52:a1:b0"
          - run:
             name: Deploy Over SSH to VPS server
             command: |
               ssh -t $SSH_USER_VPS@$SSH_HOST_VPS "cd /var/www/html/vps/public_html/inspirecms/ && git pull origin master && composer install && php artisan module:migrate && php artisan migrate && npm install && npm run dev"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
                filters:
                  branches:
                    only: master
      - deploy:

          requires:
            - build
          filters:
            branches:
              only: master