version: '3.5'
services:
    php_inspirecms:
        image: maksim1990/laravel_inspirecms:latest
        container_name: inspirecms_php
        user: "${UID}"
        volumes:
            - ./deploy:/var/www/deploy
            - ./storage/app:/var/www/storage/app
            - data-volume:/var/www
            - ./data/composer:/.composer
            - ./logs/laravel:/var/www/var/logs:cached
            - hosts-volume:/etc/nginx/conf.d
        depends_on:
            - mysql_inspirecms
            - redis_inspirecms
    nginx_inspirecms:
        image: nginx:latest
        ports:
            - "${APP_HTTP_PORT}:80"
            - "${APP_HTTPS_PORT}:443"
        volumes:
            - ./storage/app:/var/www/storage/app
            - hosts-volume:/etc/nginx/conf.d
            - data-volume:/var/www
            - ./logs/nginx/:/var/log/nginx:cached
        depends_on:
            - php_inspirecms
    redis_inspirecms:
        image: redis:latest
        ports:
          - "${APP_REDIS_PORT}:6379"
    mysql_inspirecms:
        image: mysql:5.7.21
        environment:
            MYSQL_ROOT_PASSWORD: ${APP_MYSQL_PASSWORD}
            MYSQL_DATABASE: ${APP_MYSQL_DATABASE}
        ports:
            - "${APP_MYSQL_PORT}:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
volumes:
  data-volume:
  hosts-volume:
